### ISSUE TITLE
Cast Exception while joining with outdated client

### ISSUE THREAD

**Issue by northpl93** [Diorite/Diorite#50]
`[21:55:56 INFO][DEBUG]: Debug stacktrace (java.lang.ClassCastException: org.diorite.impl.server.connection.listeners.HandshakeListener cannot be cast to org.diorite.impl.connection.packets.login.PacketLoginServerboundListener):
[21:55:56 WARN]: java.lang.ClassCastException: org.diorite.impl.server.connection.listeners.HandshakeListener cannot be cast to org.diorite.impl.connection.packets.login.PacketLoginServerboundListener
[21:55:56 WARN]:    at org.diorite.impl.connection.packets.login.serverbound.PacketLoginServerboundStart.handle(PacketLoginServerboundStart.java:40)
[21:55:56 WARN]:    at org.diorite.impl.connection.CoreNetworkManager.channelRead0(CoreNetworkManager.java:287)
[21:55:56 WARN]:    at org.diorite.impl.connection.CoreNetworkManager.channelRead0(CoreNetworkManager.java:62)
[21:55:56 WARN]:    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[21:55:56 WARN]:    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
[21:55:56 WARN]:    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
[21:55:56 WARN]:    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
[21:55:56 WARN]:    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
[21:55:56 WARN]:    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
[21:55:56 WARN]:    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
[21:55:56 WARN]:    at org.diorite.impl.connection.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:180)
[21:55:56 WARN]:    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
[21:55:56 WARN]:    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
[21:55:56 WARN]:    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
[21:55:56 WARN]:    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
[21:55:56 WARN]:    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
[21:55:56 WARN]:    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
[21:55:56 WARN]:    at org.diorite.impl.connection.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:180)
[21:55:56 WARN]:    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
[21:55:56 WARN]:    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
[21:55:56 WARN]:    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
[21:55:56 WARN]:    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
[21:55:56 WARN]:    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
[21:55:56 WARN]:    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
[21:55:56 WARN]:    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
[21:55:56 WARN]:    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
[21:55:56 WARN]:    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
[21:55:56 WARN]:    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
[21:55:56 WARN]:    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
[21:55:56 WARN]:    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
[21:55:56 WARN]:    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
[21:55:56 WARN]:    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
[21:55:56 WARN]:    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
[21:55:56 WARN]:    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
[21:55:56 WARN]:    at java.lang.Thread.run(Thread.java:745)`

**Comment by XakepSDK** [comment]
How to reproduce this error? I want contribute.

**Comment by northpl93** [comment]
Simply connect to server using unsupported Minecraft version. Current protocol version is 110 (MC 1.9.4), so 109 (MC 1.9.2 and lower) will indicate that error.
This stacktrace is logged only if you run server in debug mode (java -jar server.jar -debug)!

**Comment by mibac138** [comment]
@NorthPL. Fixed.
